using UnityEngine;

public class monedaSpawner : MonoBehaviour
{
    public GameObject monedaPrefab; // Prefab de la moneda
    public float intervaloSpawn = 2f; // Intervalo de tiempo entre spawns
    public float rangoX = 10f; // Rango en el eje X donde se generar치n las monedas

    private float tiempoSiguienteSpawn; // Tiempo para el pr칩ximo spawn

    void Start()
    {
        // Inicializar el tiempo para el primer spawn
        tiempoSiguienteSpawn = Time.time + intervaloSpawn;
    }

    void Update()
    {
        // Verificar si es hora de generar una nueva moneda
        if (Time.time >= tiempoSiguienteSpawn)
        {
            SpawnMoneda();
            // Configurar el tiempo para el siguiente spawn
            tiempoSiguienteSpawn = Time.time + intervaloSpawn;
        }
    }

    void SpawnMoneda()
    {
        // Generar una posici칩n aleatoria en el eje X dentro del rango
        float posicionX = Random.Range(-rangoX, rangoX);
        Vector3 posicionSpawn = new Vector3(posicionX, transform.position.y, transform.position.z);

        // Instanciar la moneda en la posici칩n generada
        Instantiate(monedaPrefab, posicionSpawn, Quaternion.identity);
    }
}
